### ISSUE TITLE
Licencing possible Issue.

### ISSUE THREAD

**Issue by evolvingfridge** [bennr01/neat-python#7]
Hey, I might be wrong, can find exactly where I was reading it. But remember you mentioned somewhere you used code that was without any licences. I just find out such code is all under copyright of owner him self (as I understood). Thought it is good idea to mention it.

**Comment by bennr01** [comment]
@d0pa you are right about the copyright, but i think i checked all external code snippets i used for the license.
Do you mean the code used in `distributed.py`? The code i used there was based on code from a website, but the code snippets on the website are all licensed under an open source license. I wrote a note about this in `distributed.py`.

**Comment by evolvingfridge** [comment]
ok, I was thinking you took code from github that was without licences ;)
