### ISSUE TITLE
hidden layer

### ISSUE THREAD

**Issue by ixenion** [bennr01/neat-python#9]
does neat support only 1 hidden layer or multiple hidden layers?

**Comment by bennr01** [comment]
If I recall correctly, neat-python only uses a single hidden layer.

**Comment by ixenion** [comment]
This is bad..
thanks for reply

**Comment by bennr01** [comment]
Well, to clarify: there isn't really a layer as nodes in the hidden "layer" can connect between themselves. Practically this means that there **could** be any number of layers developing, albeit no clear connection structure (e.g. each layer can only receive input from the previous layer and output to the next) is enforced. This isn't as efficient as a layer based system, but should still be *capable* of generating a network with the same "intelligence".

**Comment by ixenion** [comment]
what exactly should I do to make this?
And there is another thought: theoretically we can connect two AIs (first AI output to second AI input)
